version: '3'

tasks:
  default:
    cmds:
    - task build
    - task deploy
  build:
    cmds:
    - sam build --cached
  deploy:
    cmds:
    - sam deploy --no-confirm-changeset --resolve-image-repos
