AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  OpenAIFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./openai
    Properties:
      Environment:
        Variables:
          DYNAMO_DB_TABLE: !Ref PancakeTable
          SECRET_ARN: !Ref PancakeSecrets
          VECTOR_BUCKET: !Ref VectorBucket
      Events:
        LINEWebHook:
          Type: Api
          Properties:
            Path: /post
            Method: post
      PackageType: Image
      Policies:
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      - arn:aws:iam::aws:policy/SecretsManagerReadWrite

  VectorFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./vector
    Properties:
      Environment:
        Variables:
          SECRET_ARN: !Ref PancakeSecrets
          VECTOR_BUCKET: !Ref VectorBucket
      Events:
        S3:
          Type: S3
          Properties:
            Bucket: !Ref PDFBucket
            Events: s3:ObjectCreated:*
      MemorySize: 512
      PackageType: Image
      Policies:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Timeout: 60

  PDFBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
        - Status: Enabled
          ExpirationInDays: 1

  VectorBucket:
    Type: AWS::S3::Bucket

  PancakeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: id
        KeyType: HASH

  PancakeSecrets:
    Type: AWS::SecretsManager::Secret

Outputs:
  OpenAIEndpoint:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/post/"
