AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  OpenAIFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - x86_64
      CodeUri: openai/
      Environment:
        Variables:
          DYNAMO_DB_TABLE: !Ref PancakeTable
          SECRET_ARN: !Ref PancakeSecrets
      Events:
        LINEWebHook:
          Type: Api
          Properties:
            Path: /post
            Method: post
      Handler: app.lambda_handler
      Policies:
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Runtime: python3.11

  VectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - x86_64
      CodeUri: vector/
      Environment:
        Variables:
          SECRET_ARN: !Ref PancakeSecrets
      Handler: app.lambda_handler
      Policies:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Runtime: python3.11

  PancakeBucket:
    Type: AWS::S3::Bucket

  PancakeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: id
        KeyType: HASH

  PancakeSecrets:
    Type: AWS::SecretsManager::Secret

Outputs:
  OpenAIEndpoint:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/post/"
