AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  OpenAIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: openai/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        LINEWebHook:
          Type: Api
          Properties:
            Path: /post
            Method: post
      Policies:
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      - arn:aws:iam::aws:policy/SecretsManagerReadWrite

  VectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: vector/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/SecretsManagerReadWrite

  TheBucket:
    Type: AWS::S3::Bucket

  TheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        AttributeName: id
        KeyType: HASH

  TheSecrets:
    Type: AWS::SecretsManager::Secret

Outputs:
  OpenAIEndpoint:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
