AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  LINEBotLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: python3.11
    Properties:
      CompatibleRuntimes:
      - python3.11
      ContentUri: line_bot_layer/

  LlamaIndexLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: python3.11
    Properties:
      CompatibleRuntimes:
      - python3.11
      ContentUri: llama_index_layer/

  OpenAILayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: python3.11
    Properties:
      CompatibleRuntimes:
      - python3.11
      ContentUri: openai_layer/

  OpenAIFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - x86_64
      CodeUri: openai/
      Environment:
        Variables:
          DYNAMO_DB_TABLE: !Ref PancakeTable
          SECRET_ARN: !Ref PancakeSecrets
          VECTOR_BUCKET: !Ref VectorBucket
      Events:
        LINEWebHook:
          Type: Api
          Properties:
            Path: /post
            Method: post
      Handler: app.lambda_handler
      Layers:
      - !Ref LINEBotLayer
      - !Ref OpenAILayer
      Policies:
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Runtime: python3.11

  VectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - x86_64
      CodeUri: vector/
      Environment:
        Variables:
          SECRET_ARN: !Ref PancakeSecrets
          VECTOR_BUCKET: !Ref VectorBucket
      Events:
        S3:
          Type: S3
          Properties:
            Bucket: !Ref PDFBucket
            Events: s3:ObjectCreated:*
      Handler: app.lambda_handler
      Layers:
      - !Ref LlamaIndexLayer
      Policies:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Runtime: python3.11

  PDFBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
        - Status: Enabled
          ExpirationInDays: 1

  VectorBucket:
    Type: AWS::S3::Bucket

  PancakeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: id
        KeyType: HASH

  PancakeSecrets:
    Type: AWS::SecretsManager::Secret

Outputs:
  OpenAIEndpoint:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/post/"
